/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonsanddragons;

/**
 *
 * @author JaneW
 */
public class D2CharacterView extends javax.swing.JPanel {
    
    private D2Character character;
    private D2WeaponView viewWeapon;

    /**
     * Creates new form D2CharacterView
     */
    public D2CharacterView() {
        initComponents();
        viewWeapon = new D2WeaponView();
        this.add(viewWeapon);
        viewWeapon.setBounds(124,36,150,250);
    }

    
    public void setView(D2Character characterNew) {
        character = characterNew;
        lblName.setText(character.getName());
        lblDesc.setText(character.getD2Class() + " " + character.getRace());
        lblLevel.setText("Level:" + Integer.toString(character.getLevel()));
        lblHP.setText("HP:" + Integer.toString(character.getHP()));
        lblAC.setText("AC:" + Integer.toString(character.getArmourClass()));
        viewWeapon.setItem(characterNew.getWeapon(D2WeaponSlot.RIGHT_HAND));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(character.getImageFileName())));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblHP = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(116, 102, 51));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name");

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dungeonsanddragons/resources/characters/naeriem.png"))); // NOI18N
        lblImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblLevel.setForeground(new java.awt.Color(204, 204, 0));
        lblLevel.setText("Level:");

        lblHP.setForeground(new java.awt.Color(204, 204, 0));
        lblHP.setText("HP:");

        lblAC.setForeground(new java.awt.Color(204, 204, 0));
        lblAC.setText("AC:");

        lblDesc.setForeground(new java.awt.Color(204, 204, 0));
        lblDesc.setText("Desc:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAC))
                    .addComponent(lblImage))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblLevel)
                    .addComponent(lblHP)
                    .addComponent(lblAC)
                    .addComponent(lblDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
