/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonsanddragons;
import java.awt.Color;
/**
 *
 * @author JaneW
 */
public class D2CharacterTabbedView extends javax.swing.JPanel {
    
    private D2Character character;
    private D2WeaponView viewWeapon;
    private D2CharacterStatsView viewStats;
    private D2EquipmentView viewArmour;

    /**
     * Creates new form D2CharacterView
     */
    public D2CharacterTabbedView() {
        initComponents();
        viewWeapon = new D2WeaponView();
        tabViews.addTab("W",viewWeapon);
        
        viewStats = new D2CharacterStatsView();
        tabViews.addTab("S",viewStats);
        
        viewArmour = new D2EquipmentView();
        tabViews.addTab("E",viewArmour);
        
        
        
        
        
        tabViews.setBounds(124,36,150,250);
    }

    
    public void setView(D2Character characterNew) {
        character = characterNew;
        
        characterNew.print();
        System.out.println(characterNew.getImageFileName());

        lblName.setText(character.getName());
        lblDesc.setText(character.getRace() + " " + character.getD2Class());
        lblLevel.setText("Level:" + Integer.toString(character.getLevel()));
        lblHP.setText("HP:" + Integer.toString(character.getHP()));
        lblAC.setText("AC:" + Integer.toString(character.getArmourClass()));
        viewWeapon.setItem(characterNew.getWeapon(D2WeaponSlot.RIGHT_HAND));
        viewStats.setView(characterNew);
        viewArmour.setItem(characterNew.getEquipment(D2EquipmentSlot.BODY));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(character.getImageFileName())));
        
        // Set colour of HP text best on current HP
        Color colorHP;

        if(character.getHP()<=0) {
            colorHP = new Color(255,0,0);
        }
        else if(character.getHP()<=4) {
            colorHP = new Color(245,167,0);
        }
        else {
            colorHP = new Color(255,255,255);
        }
        lblHP.setForeground(colorHP);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblHP = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        tabViews = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(116, 102, 51));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name");

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dungeonsanddragons/resources/characters/naeriem.png"))); // NOI18N
        lblImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblLevel.setForeground(new java.awt.Color(204, 204, 0));
        lblLevel.setText("Level:");

        lblHP.setForeground(new java.awt.Color(204, 204, 0));
        lblHP.setText("HP:");

        lblAC.setForeground(new java.awt.Color(204, 204, 0));
        lblAC.setText("AC:");

        lblDesc.setForeground(new java.awt.Color(204, 204, 0));
        lblDesc.setText("Desc:");

        tabViews.setBackground(new java.awt.Color(153, 153, 153));
        tabViews.setForeground(new java.awt.Color(255, 255, 255));
        tabViews.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        tabViews.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAC))
                            .addComponent(lblImage))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(tabViews)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblLevel)
                    .addComponent(lblHP)
                    .addComponent(lblAC)
                    .addComponent(lblDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabViews))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JTabbedPane tabViews;
    // End of variables declaration//GEN-END:variables
}
