/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonsanddragons;

/**
 *
 * @author JaneW
 */
public class D2CharacterStatsView extends javax.swing.JPanel {

    /**
     * Creates new form D2CharacterStatsView
     */
    public D2CharacterStatsView() {
        initComponents();
    }
    
    public void setView(D2Character charNew) {
        
        int iXP = charNew.getXP();

        lblLevel.setText(Integer.toString(charNew.getLevel()));
        lblXP.setText(Integer.toString(iXP));
        lblHPMax.setText(Integer.toString(charNew.getMaxHP()));
        lblNextLevelXP.setText(Integer.toString(D2Rules.XPToNextLevel(iXP)) + 
                                " (" + Double.toString(D2Rules.progressToNextLevel(iXP)) + "%)");
        lblMoney.setText(charNew.getMoney().toString());
        lblSize.setText(charNew.getSize().toString());
        lblSpeed.setText(Integer.toString(charNew.getSpeed()) + " feet");
        
        
        D2CharacterStats stats = charNew.getStats();      
        lblSTR.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.STR))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.STR)) + ")");
        lblDEX.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.DEX))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.DEX)) + ")");
        lblCON.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.CON))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.CON)) + ")");
        lblWIS.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.WIS))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.WIS)) + ")");
        lblINT.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.INT))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.INT)) + ")");
        lblCHA.setText(Integer.toString(stats.getStat(D2CharacterStats.D2Abilities.CHA))
                +" (" + Integer.toString(stats.getStatModifier(D2CharacterStats.D2Abilities.CHA)) + ")");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblXP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDEX = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCON = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblWIS = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblINT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCHA = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSTR = new javax.swing.JLabel();
        lblNextLevelXP = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblHPMax = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setLabelFor(lblSTR);
        jLabel1.setText("STR:");

        lblXP.setForeground(new java.awt.Color(255, 255, 255));
        lblXP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblXP.setText("jLabel2");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setLabelFor(lblDEX);
        jLabel2.setText("DEX:");

        lblDEX.setForeground(new java.awt.Color(255, 255, 255));
        lblDEX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDEX.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setLabelFor(lblCON);
        jLabel3.setText("CON:");

        lblCON.setForeground(new java.awt.Color(255, 255, 255));
        lblCON.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCON.setText("jLabel2");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setLabelFor(lblCHA);
        jLabel4.setText("WIS:");

        lblWIS.setForeground(new java.awt.Color(255, 255, 255));
        lblWIS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWIS.setText("jLabel2");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setLabelFor(lblDEX);
        jLabel5.setText("INT:");

        lblINT.setForeground(new java.awt.Color(255, 255, 255));
        lblINT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblINT.setText("jLabel2");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setLabelFor(lblCON);
        jLabel6.setText("CHA:");

        lblCHA.setForeground(new java.awt.Color(255, 255, 255));
        lblCHA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCHA.setText("jLabel2");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setLabelFor(lblMoney);
        jLabel7.setText("Money:");

        lblMoney.setForeground(new java.awt.Color(255, 255, 255));
        lblMoney.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMoney.setText("jLabel2");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setLabelFor(lblLevel);
        jLabel8.setText("Level:");

        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLevel.setText("jLabel2");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setLabelFor(lblXP);
        jLabel9.setText("XP:");

        lblSTR.setForeground(new java.awt.Color(255, 255, 255));
        lblSTR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSTR.setText("jLabel2");

        lblNextLevelXP.setForeground(new java.awt.Color(255, 255, 255));
        lblNextLevelXP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNextLevelXP.setText("jLabel2");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setLabelFor(lblNextLevelXP);
        jLabel10.setText("Next level:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setLabelFor(lblSize);
        jLabel11.setText("Size:");

        lblSize.setForeground(new java.awt.Color(255, 255, 255));
        lblSize.setText("jLabel12");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setLabelFor(lblSpeed);
        jLabel12.setText("Speed:");

        lblSpeed.setForeground(new java.awt.Color(255, 255, 255));
        lblSpeed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSpeed.setText("jLabel2");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setLabelFor(lblHPMax);
        jLabel13.setText("Max HP:");

        lblHPMax.setForeground(new java.awt.Color(255, 255, 255));
        lblHPMax.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDEX)
                                    .addComponent(lblCON)
                                    .addComponent(lblSTR))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWIS)
                                    .addComponent(lblINT)
                                    .addComponent(lblCHA)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMoney))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblXP)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLevel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSize))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNextLevelXP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSpeed))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHPMax)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblLevel)
                    .addComponent(jLabel11)
                    .addComponent(lblSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblXP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblNextLevelXP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblWIS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblINT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCHA)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblSTR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblDEX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblCON))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblSpeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblHPMax))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCHA;
    private javax.swing.JLabel lblCON;
    private javax.swing.JLabel lblDEX;
    private javax.swing.JLabel lblHPMax;
    private javax.swing.JLabel lblINT;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblNextLevelXP;
    private javax.swing.JLabel lblSTR;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblWIS;
    private javax.swing.JLabel lblXP;
    // End of variables declaration//GEN-END:variables
}
